FROM node:18
# Create app directory
WORKDIR /usr/src/parent/frontend
COPY ./frontend/package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev
# Bundle app source
COPY ./frontend .
EXPOSE 3000
CMD [ "npm", "run", "start" ]