version: '3'

services:

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27016:27017'
    volumes:
      - ./.docker-data/.mogndo-data:/data/db
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq/

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    depends_on:
    - api

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3002:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
    - prometheus

  api:
    container_name: data_server
    build:
      context: ./
      dockerfile: Dockerfile.data_server
    ports:
    - "3001:3001"
    depends_on:
    - mongo
    #remove comments for development note - will not work with docker need to comment out
    #volumes: 
    #- ./data_server:/parent/data_server
    #- ./data_server/node_modules:/parent/data_server/node_modules


  client:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
    - api
    stdin_open: true

  data_analyzer:
    container_name: data_analyzer
    build:
      context: ./
      dockerfile: Dockerfile.data_analyzer
    depends_on:
    - mongo
    - rabbitmq
  
  data_extractor:
    container_name: data_extractor
    build:
      context: ./
      dockerfile: Dockerfile.data_extractor
    depends_on:
    - rabbitmq

  nginx:
    depends_on:
    - api
    - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
    - "3050:80"

volumes:
  prom_data:
