FROM node:18
# Create app directory
WORKDIR /usr/src/parent/data_analyzer
COPY ./data_extractor/package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev
# Bundle app source
COPY ./data_analyzer .
WORKDIR /usr/src/parent/config
COPY ./config .
WORKDIR /usr/src/parent/data_analyzer
CMD [ "npm", "run", "docker" ]