version: '3'

services:

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27016:27017'
    volumes:
      - ./.docker-data/.mogndo-data:/data/db
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq/

  api:
    container_name: data_server
    build:
      context: ./
      dockerfile: Dockerfile.data_server
    ports:
    - "3001:3001"
    depends_on:
    - mongo
    volumes: 
    - ./data_server:/parent/data_server
    - ./data_server/node_modules:/parent/data_server/node_modules


  client:
    container_name: frontend
    build:
      context: ./frontend
    #ports:
    #  - "3000:3000"
    depends_on:
    - api
    stdin_open: true

  data_analyzer:
    container_name: data_analyzer
    build:
      context: ./
      dockerfile: Dockerfile.data_analyzer
    depends_on:
    - mongo
    - rabbitmq
  
  data_extractor:
    container_name: data_extractor
    build:
      context: ./
      dockerfile: Dockerfile.data_extractor
    depends_on:
    - rabbitmq

  nginx:
    depends_on:
    - api
    - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
    - "3050:80"



