FROM node:18
# Create app directory
WORKDIR /usr/src/parent/data_extractor
COPY ./data_extractor/package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev
# Bundle app source
COPY ./data_extractor .
WORKDIR /usr/src/parent/components
COPY ./components/package*.json ./
RUN npm install
COPY ./components .
WORKDIR /usr/src/parent/data_extractor
CMD [ "npm", "run", "docker" ]
