version: '3'
  
services:
   mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27016:27017'
    #to keep data permanent remove comments on below volume
    #volumes:
    #  - ./.docker-data/data:/data/db
